# Generated by Django 2.0.1 on 2018-01-27 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iimv', '0002_auto_20180127_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photogallery',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='updates',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 27, 16, 45, 36, 129455)),
        ),
    ]
