# Generated by Django 2.0.1 on 2018-01-29 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iimv', '0003_auto_20180127_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='executivemembers',
            name='srn',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='photogallery',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='photogallery',
            name='srn',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='updates',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 29, 22, 2, 8, 486637)),
        ),
    ]
