# Generated by Django 2.0.1 on 2018-01-29 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iimv', '0005_auto_20180129_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executivemembers',
            name='images',
            field=models.ImageField(upload_to='static/executivememberslist/'),
        ),
        migrations.AlterField(
            model_name='photogallery',
            name='image',
            field=models.ImageField(upload_to='static/photogallery/'),
        ),
        migrations.AlterField(
            model_name='updates',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 29, 22, 12, 35, 52005)),
        ),
    ]
